// Generates src/environments/environment.ts from the .env file so the browser
// bundle gets real values (Angular does NOT read .env at build time itself).
// Run automatically via the pre* npm scripts; pass --prod for a production build.
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const isProd = process.argv.includes('--prod');

/** Minimal .env parser (KEY=VALUE, # comments, optional quotes). */
function parseEnv(file) {
  const out = {};
  if (!existsSync(file)) {
    return out;
  }
  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const eq = trimmed.indexOf('=');
    if (eq === -1) {
      continue;
    }
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

// Real process env wins over the .env file (handy for CI overrides).
const env = { ...parseEnv(resolve(root, '.env')), ...process.env };
const apiUrl = env.APP_URL;

const target = resolve(root, 'src/environments/environment.ts');
const content = `// GENERATED by scripts/set-env.mjs from .env — DO NOT EDIT.
// Change values in .env (see .env.example), not here.
export const environment = {
  production: ${isProd},
  apiUrl: ${JSON.stringify(apiUrl)},
};
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, content);
console.log(
  `[set-env] wrote src/environments/environment.ts (production=${isProd}, apiUrl=${apiUrl})`,
);
